name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  integration_tests:
    name: Build and Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode 11.6
        run: sudo xcode-select -s /Applications/Xcode_11.6.app
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6" # Version range or exact version of a Ruby version to use, using semvers version range syntax.
          bundler-cache: true
      - name: Installing GNU coreutils
        run: brew install coreutils
      - name: Build and Test
        run: bundle exec rake build_test_dumper spec
